name: Build and Deploy to IONOS
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USER_POMODORO }}
          password: ${{ secrets.SFTP_PASSWORD_POMODORO }}
          port: 22
          local_path: './dist/'    # Archivos generados por el build
          remote_path: '/public/openPomodoro/'  # Destino en IONOS
          sftp_only: true
